In [2]:
import pandas as pd

In [3]:
file_path = 'data/pb_winning_numbers_03-18-2017.csv'

In [4]:
pb = pd.read_csv(file_path)

In [17]:
#drop anything less than 01-01-2010

pb_clean = pb[pb['DrawDate'] < '01/01/2010']
pb

        DrawDate  WB1  WB2  WB3  WB4  WB5  PB    PP
0     03/15/2017   30   16   41   48   53  16   3.0
1     03/11/2017   57   41   50   26    1  11   2.0
2     03/08/2017   42   23   59   46   33   4   2.0
3     03/04/2017    2   22   63   19   18  19   3.0
4     03/01/2017   16   10   52   40   55  17  10.0
5     02/25/2017    6   62   32   47   65  19   2.0
6     02/22/2017   52   10   61   28   13   2   2.0
7     02/18/2017    9    3   33    7   31  20   3.0
8     02/15/2017   33    5   42   38   28  19   2.0
9     02/11/2017   37   64   17    9    5   2   2.0
10    02/08/2017   49   20   42   14   66   5   2.0
11    02/04/2017   52   17   16   13    6  25   3.0
12    02/01/2017    9   60   64   43   57  10   2.0
13    01/28/2017   39   12   49   69   20  17   2.0
14    01/25/2017   18   62   66   68   28  22   2.0
15    01/21/2017   45   25   23   67   52   2   2.0
16    01/18/2017   41    9   58   40   53  12   2.0
17    01/14/2017   55   69   23   64   59  13   5.0
18    01/11/2017    1   16   13   43    3  24   2.0
19    01/07/2017   37   63   12   24    3  10   2.0
20    01/04/2017   17   16   42   41   29   4   3.0
21    12/31/2016    1   28    3   67   57   9   2.0
22    12/28/2016   30   23   44   58   16   4   2.0
23    12/24/2016   38   52   42   51   28  21   2.0
24    12/21/2016   25   68   40   54   33   3   5.0
25    12/17/2016   16   40    8   48    1  10   2.0
26    12/14/2016   39   18   66   37   26  15   3.0
27    12/10/2016   32   21   12   44   66  15   2.0
28    12/07/2016   49   64   48   41   53  20   2.0
29    12/03/2016   27   26   33    8   10  22   2.0
...          ...  ...  ...  ...  ...  ...  ..   ...
1992  02/11/1998   37   34   33   25   35  35   NaN
1993  02/07/1998   40   12   15    5   27  14   NaN
1994  02/04/1998   30   25   12    8   21  20   NaN
1995  01/31/1998   13   36   48    7   11  18   NaN
1996  01/28/1998   23   48   36   15   31  12   NaN
1997  01/24/1998    7   23   15   28   36  10   NaN
1998  01/21/1998   31   32   23    1   26  33   NaN
1999  01/17/1998   28    9   49   38   29   6   NaN
2000  01/14/1998   16    9    6   28   38  13   NaN
2001  01/10/1998   17    9    7   44   20  25   NaN
2002  01/07/1998   18    4   30   37    3  23   NaN
2003  01/03/1998    4    9   27    7   32   6   NaN
2004  12/31/1997   27   14    6    4    5   6   NaN
2005  12/27/1997   14   48   15   36    9  17   NaN
2006  12/24/1997   28   16   35   34    3  14   NaN
2007  12/20/1997   23   11   12   17   10   7   NaN
2008  12/17/1997    3    5   45   18   13  20   NaN
2009  12/13/1997   44   41   46   35    5  27   NaN
2010  12/10/1997   18   21   28   41    4   3   NaN
2011  12/06/1997   15   26   28    8   43  36   NaN
2012  12/03/1997   18    9   14   47   42  32   NaN
2013  11/29/1997   11   27   13    2   31  23   NaN
2014  11/26/1997   15   46   34   23   40  35   NaN
2015  11/22/1997   22   31    3    7   14   2   NaN
2016  11/19/1997   19   10   48    3   21  22   NaN
2017  11/15/1997   32    7   45   21   26   8   NaN
2018  11/12/1997   41   14   13   29   16   1   NaN
2019  11/08/1997   40   17   21    7   49  37   NaN
2020  11/05/1997    2   19   35   24   28  26   NaN
2021  11/01/1997   37   28   33   22   25  20   NaN

[2022 rows x 8 columns]

In [20]:
pb.to_csv('powerball_cleaned.csv')