In [1]:
import pandas as pd

In [2]:
file_path = 'data/pb_winning_numbers_03-18-2017.csv'

In [3]:
pb = pd.read_csv(file_path)
pb_clean = pb[pb['DrawDate'] < '01/01/2010']
pb

        DrawDate  WB1  WB2  WB3  WB4  WB5  PB    PP
0     03/15/2017   30   16   41   48   53  16   3.0
1     03/11/2017   57   41   50   26    1  11   2.0
2     03/08/2017   42   23   59   46   33   4   2.0
3     03/04/2017    2   22   63   19   18  19   3.0
4     03/01/2017   16   10   52   40   55  17  10.0
5     02/25/2017    6   62   32   47   65  19   2.0
6     02/22/2017   52   10   61   28   13   2   2.0
7     02/18/2017    9    3   33    7   31  20   3.0
8     02/15/2017   33    5   42   38   28  19   2.0
9     02/11/2017   37   64   17    9    5   2   2.0
10    02/08/2017   49   20   42   14   66   5   2.0
11    02/04/2017   52   17   16   13    6  25   3.0
12    02/01/2017    9   60   64   43   57  10   2.0
13    01/28/2017   39   12   49   69   20  17   2.0
14    01/25/2017   18   62   66   68   28  22   2.0
15    01/21/2017   45   25   23   67   52   2   2.0
16    01/18/2017   41    9   58   40   53  12   2.0
17    01/14/2017   55   69   23   64   59  13   5.0
18    01/11/2017    1   16   13   43    3  24   2.0
19    01/07/2017   37   63   12   24    3  10   2.0
20    01/04/2017   17   16   42   41   29   4   3.0
21    12/31/2016    1   28    3   67   57   9   2.0
22    12/28/2016   30   23   44   58   16   4   2.0
23    12/24/2016   38   52   42   51   28  21   2.0
24    12/21/2016   25   68   40   54   33   3   5.0
25    12/17/2016   16   40    8   48    1  10   2.0
26    12/14/2016   39   18   66   37   26  15   3.0
27    12/10/2016   32   21   12   44   66  15   2.0
28    12/07/2016   49   64   48   41   53  20   2.0
29    12/03/2016   27   26   33    8   10  22   2.0
...          ...  ...  ...  ...  ...  ...  ..   ...
1992  02/11/1998   37   34   33   25   35  35   NaN
1993  02/07/1998   40   12   15    5   27  14   NaN
1994  02/04/1998   30   25   12    8   21  20   NaN
1995  01/31/1998   13   36   48    7   11  18   NaN
1996  01/28/1998   23   48   36   15   31  12   NaN
1997  01/24/1998    7   23   15   28   36  10   NaN
1998  01/21/1998   31   32   23    1   26  33   NaN
1999  01/17/1998   28    9   49   38   29   6   NaN
2000  01/14/1998   16    9    6   28   38  13   NaN
2001  01/10/1998   17    9    7   44   20  25   NaN
2002  01/07/1998   18    4   30   37    3  23   NaN
2003  01/03/1998    4    9   27    7   32   6   NaN
2004  12/31/1997   27   14    6    4    5   6   NaN
2005  12/27/1997   14   48   15   36    9  17   NaN
2006  12/24/1997   28   16   35   34    3  14   NaN
2007  12/20/1997   23   11   12   17   10   7   NaN
2008  12/17/1997    3    5   45   18   13  20   NaN
2009  12/13/1997   44   41   46   35    5  27   NaN
2010  12/10/1997   18   21   28   41    4   3   NaN
2011  12/06/1997   15   26   28    8   43  36   NaN
2012  12/03/1997   18    9   14   47   42  32   NaN
2013  11/29/1997   11   27   13    2   31  23   NaN
2014  11/26/1997   15   46   34   23   40  35   NaN
2015  11/22/1997   22   31    3    7   14   2   NaN
2016  11/19/1997   19   10   48    3   21  22   NaN
2017  11/15/1997   32    7   45   21   26   8   NaN
2018  11/12/1997   41   14   13   29   16   1   NaN
2019  11/08/1997   40   17   21    7   49  37   NaN
2020  11/05/1997    2   19   35   24   28  26   NaN
2021  11/01/1997   37   28   33   22   25  20   NaN

[2022 rows x 8 columns]

In [4]:
texas_url = "https://www.txlottery.org/export/sites/lottery/Games/Powerball/Winning_Numbers/index.html_1444349437.html"

texas_data = pd.read_html(texas_url)
texas_df = texas_data[0]
texas_df.rename(columns={'Draw Date':'DrawDate', 'Winning Numbers':'winning_numbers', 'Powerball':'powerball', 'Power Play':'power_play','Estimated Jackpot':'estimated_jackpot', 'Jackpot Winners':'jackpot_winner', 'Jackpot Option':'jackpot_option'}, inplace=True)
texas_df = texas_df.drop(columns=['winning_numbers'])

clean_texas = texas_df[['DrawDate', 'estimated_jackpot', 'jackpot_winner', 'jackpot_option']]
clean_texas.describe()

          DrawDate estimated_jackpot jackpot_winner jackpot_option
count          967               965            965              2
unique         967               275              3              1
top     10/07/2015       $40 Million           Roll            CVO
freq             1                77            864              2

In [5]:
clean_texas

       DrawDate estimated_jackpot       jackpot_winner jackpot_option
0    05/01/2019      $181 Million                 Roll            NaN
1    04/27/2019      $166 Million                 Roll            NaN
2    04/24/2019      $150 Million                 Roll            NaN
3    04/20/2019      $136 Million                 Roll            NaN
4    04/17/2019      $118 Million                 Roll            NaN
5    04/13/2019      $101 Million                 Roll            NaN
6    04/10/2019       $84 Million                 Roll            NaN
7    04/06/2019       $68 Million                 Roll            NaN
8    04/03/2019       $54 Million                 Roll            NaN
9    03/30/2019       $40 Million                 Roll            NaN
10   03/27/2019      $750 Million  Out of State Winner            NaN
11   03/23/2019      $625 Million                 Roll            NaN
12   03/20/2019      $550 Million                 Roll            NaN
13   03/16/2019      $495 Million                 Roll            NaN
14   03/13/2019      $448 Million                 Roll            NaN
15   03/09/2019      $414 Million                 Roll            NaN
16   03/06/2019      $381 Million                 Roll            NaN
17   03/02/2019      $348 Million                 Roll            NaN
18   02/27/2019      $322 Million                 Roll            NaN
19   02/23/2019      $304 Million                 Roll            NaN
20   02/20/2019      $282 Million                 Roll            NaN
21   02/16/2019      $260 Million                 Roll            NaN
22   02/13/2019      $242 Million                 Roll            NaN
23   02/09/2019      $224 Million                 Roll            NaN
24   02/06/2019      $204 Million                 Roll            NaN
25   02/02/2019      $191 Million                 Roll            NaN
26   01/30/2019      $174 Million                 Roll            NaN
27   01/26/2019      $161 Million                 Roll            NaN
28   01/23/2019      $144 Million                 Roll            NaN
29   01/19/2019      $129 Million                 Roll            NaN
..          ...               ...                  ...            ...
937  05/15/2010      $120 Million                 Roll            NaN
938  05/12/2010       $97 Million                 Roll            NaN
939  05/08/2010       $80 Million                 Roll            NaN
940  05/05/2010       $60 Million                 Roll            NaN
941  05/01/2010       $45 Million                 Roll            NaN
942  04/28/2010       $30 Million                 Roll            NaN
943  04/24/2010       $20 Million                 Roll            NaN
944  04/21/2010      $252 Million  Out of State Winner            NaN
945  04/17/2010      $212 Million                 Roll            NaN
946  04/14/2010      $175 Million                 Roll            NaN
947  04/10/2010      $150 Million                 Roll            NaN
948  04/07/2010      $125 Million                 Roll            NaN
949  04/03/2010      $103 Million                 Roll            NaN
950  03/31/2010       $81 Million                 Roll            NaN
951  03/27/2010       $60 Million                 Roll            NaN
952  03/24/2010       $43 Million                 Roll            NaN
953  03/20/2010       $28 Million                 Roll            NaN
954  03/17/2010       $20 Million                 Roll            NaN
955  03/13/2010      $200 Million  Out of State Winner            NaN
956  03/10/2010      $170 Million                 Roll            NaN
957  03/06/2010      $139 Million                 Roll            NaN
958  03/03/2010      $114 Million                 Roll            NaN
959  02/27/2010       $95 Million                 Roll            NaN
960  02/24/2010       $76 Million                 Roll            NaN
961  02/20/2010       $57 Million                 Roll            NaN
962  02/17/2010       $40 Million                 Roll            NaN
963  02/13/2010       $25 Million                 Roll            NaN
964  02/10/2010       $20 Million                 Roll            NaN
965  02/06/2010      $140 Million  Out of State Winner            NaN
966  02/03/2010      $115 Million                 Roll            NaN

[967 rows x 4 columns]

In [6]:
df = pb.merge(clean_texas, how='inner')

In [7]:
df

,DrawDate,WB1,WB2,WB3,WB4,WB5,PB,PP,estimated_jackpot,jackpot_winner,jackpot_option
0,03/15/2017,30,16,41,48,53,16,3.0,$123 Million,Roll,NaN
1,03/11/2017,57,41,50,26,1,11,2.0,$104 Million,Roll,NaN
2,03/08/2017,42,23,59,46,33,4,2.0,$85 Million,Roll,NaN
3,03/04/2017,2,22,63,19,18,19,3.0,$68 Million,Roll,NaN
4,03/01/2017,16,10,52,40,55,17,10.0,$53 Million,Roll,NaN
5,02/25/2017,6,62,32,47,65,19,2.0,$40 Million,Roll,NaN
6,02/22/2017,52,10,61,28,13,2,2.0,$403 Million,Out of State Winner,NaN
7,02/18/2017,9,3,33,7,31,20,3.0,$349 Million,Roll,NaN
8,02/15/2017,33,5,42,38,28,19,2.0,$310 Million,Roll,NaN
9,02/11/2017,37,64,17,9,5,2,2.0,$285 Million,Roll,NaN
10,02/08/2017,49,20,42,14,66,5,2.0,$255 Million,Roll,NaN
11,02/04/2017,52,17,16,13,6,25,3.0,$229 Million,Roll,NaN
12,02/01/2017,9,60,64,43,57,10,2.0,$206 Million,Roll,NaN
13,01/28/2017,39,12,49,69,20,17,2.0,$187 Million,Roll,NaN
14,01/25/2017,18,62,66,68,28,22,2.0,$170 Million,Roll,NaN
15,01/21/2017,45,25,23,67,52,2,2.0,$153 Million,Roll,NaN
16,01/18/2017,41,9,58,40,53,12,2.0,$135 Million,Roll,NaN
17,01/14/2017,55,69,23,64,59,13,5.0,$121 Million,Roll,NaN
18,01/11/2017,1,16,13,43,3,24,2.0,$106 Million,Roll,NaN
19,01/07/2017,37,63,12,24,3,10,2.0,$94 Million,Roll,NaN
20,01/04/2017,17,16,42,41,29,4,3.0,$80 Million,Roll,NaN
21,12/31/2016,1,28,3,67,57,9,2.0,$70 Million,Roll,NaN
22,12/28/2016,30,23,44,58,16,4,2.0,$60 Million,Roll,NaN
23,12/24/2016,38,52,42,51,28,21,2.0,$50 Million,Roll,NaN
24,12/21/2016,25,68,40,54,33,3,5.0,$40 Million,Roll,NaN
25,12/17/2016,16,40,8,48,1,10,2.0,$119 Million,Out of State Winner,NaN
26,12/14/2016,39,18,66,37,26,15,3.0,$100 Million,Roll,NaN
27,12/10/2016,32,21,12,44,66,15,2.0,$85 Million,Roll,NaN
28,12/07/2016,49,64,48,41,53,20,2.0,$67 Million,Roll,NaN
29,12/03/2016,27,26,33,8,10,22,2.0,$54 Million,Roll,NaN
...,...,...,...,...,...,...,...,...,...,...,...
713,05/15/2010,28,15,36,23,21,20,2.0,$120 Million,Roll,NaN
714,05/12/2010,52,58,53,37,51,38,2.0,$97 Million,Roll,NaN
715,05/08/2010,41,5,57,34,22,31,5.0,$80 Million,Roll,NaN
716,05/05/2010,47,13,34,40,57,11,4.0,$60 Million,Roll,NaN
717,05/01/2010,23,25,16,49,58,20,4.0,$45 Million,Roll,NaN
718,04/28/2010,28,44,12,22,25,24,4.0,$30 Million,Roll,NaN
719,04/24/2010,57,56,1,53,12,5,2.0,$20 Million,Roll,NaN
720,04/21/2010,11,34,55,41,49,20,2.0,$252 Million,Out of State Winner,NaN
721,04/17/2010,22,41,49,21,5,15,5.0,$212 Million,Roll,NaN
722,04/14/2010,14,6,32,52,38,20,3.0,$175 Million,Roll,NaN
723,04/10/2010,21,22,52,49,58,34,2.0,$150 Million,Roll,NaN
724,04/07/2010,36,52,44,4,40,33,2.0,$125 Million,Roll,NaN
725,04/03/2010,15,59,52,10,31,4,4.0,$103 Million,Roll,NaN
726,03/31/2010,13,45,54,5,17,12,5.0,$81 Million,Roll,NaN
727,03/27/2010,21,7,32,52,44,10,4.0,$60 Million,Roll,NaN
728,03/24/2010,14,49,39,24,20,7,3.0,$43 Million,Roll,NaN
729,03/20/2010,9,36,44,45,39,9,2.0,$28 Million,Roll,NaN
730,03/17/2010,55,26,48,45,24,8,2.0,$20 Million,Roll,NaN
731,03/13/2010,16,36,20,6,31,8,5.0,$200 Million,Out of State Winner,NaN
732,03/10/2010,41,37,17,50,21,1,2.0,$170 Million,Roll,NaN
733,03/06/2010,41,33,10,59,29,15,2.0,$139 Million,Roll,NaN
734,03/03/2010,14,49,9,7,45,23,4.0,$114 Million,Roll,NaN
735,02/27/2010,47,18,58,53,51,30,2.0,$95 Million,Roll,NaN
736,02/24/2010,50,17,57,35,4,12,2.0,$76 Million,Roll,NaN
737,02/20/2010,13,54,41,37,27,32,2.0,$57 Million,Roll,NaN
738,02/17/2010,36,7,26,8,19,15,3.0,$40 Million,Roll,NaN
739,02/13/2010,14,10,40,51,30,1,4.0,$25 Million,Roll,NaN
740,02/10/2010,29,8,37,38,5,34,5.0,$20 Million,Roll,NaN
741,02/06/2010,22,54,52,14,59,4,3.0,$140 Million,Out of State Winner,NaN
742,02/03/2010,37,52,22,36,17,24,2.0,$115 Million,Roll,NaN

In [8]:
df.to_csv('data/master_lotto.csv')

In [9]:
import pandas as pd

In [10]:
winning_state_url = 'http://portalseven.com/lottery/powerball_jackpot_winners.jsp'
    
winning_state = pd.read_html(winning_state_url)[2]
lotto_header = winning_state.iloc[0] 
winning_states_df = winning_state[1:]
winning_states_df.columns = lotto_header
winning_states_df = winning_states_df.drop(columns=['#'])

winning_states_df

,Draw Date,Jackpot Prize,Winner,State
1,"March 27, 2019",$768 Million,Unclaimed,Wisconsin
2,"December 26, 2018",$298.3 Million,David Johnson,New York
3,"October 27, 2018",$687.8 Million,Robert Bailey,New York
4,"August 11, 2018",$245.6 Million,The Sea & Sand Trust (Nandlall Mangal),New York
5,"June 20, 2018",$150.4 Million,Steven Nickell,Oregon
6,"May 19, 2018",$315.3 Million,Tayeb Souami,New Jersey
7,"March 24, 2018",$55.9 Million,The Moose Family Trust,LA
8,"March 17, 2018",$456.7 Million,Emerald Legacy Trust,Pennsylvania
9,"January 06, 2018",$559.7 Million,Good Karma Family 2018 Nominee Trust,New Hampshire
10,"October 25, 2017",$191.1 Million,292 Family Partnership,Louisiana
11,"September 16, 2017",$133.2 Million,Judy F.,Colorado
12,"August 23, 2017",$758.7 Million,Mavis Wanczyk,Massachusetts
13,"June 10, 2017",$447 Million,Jeff Lindsay,California
14,"April 01, 2017",$60 Million,Anonymous,Arizona
15,"March 22, 2017",$156 Million,Mai Xiong,Wisconsin
16,"February 22, 2017",$435.3 Million,"Bohemian Financial, LLC",Indiana
17,"December 17, 2016",$121.6 Million,Anonymous,DE
18,"November 26, 2016",$420.9 Million,Tennessee 20,Tennessee
19,"September 17, 2016",$246 Million,William and Heather ten Broeke,Georgia
20,"July 30, 2016",$487 Million,Robin Egg 2016 Nominee Trust,New Hampshire
21,"May 07, 2016",$284 Million,The Smith Family Lottery Pool,New Jersey
22,"March 02, 2016",$291.4 Million,James Stocklas,Florida
23,"January 13, 2016",$1.58 Billion,Marvin and Mae Acosta,California
24,"November 04, 2015",$144 Million,Avondale Revocable Trust,Tennessee
25,"September 30, 2015",$310 Million,Julie Leach,Michigan
26,"August 01, 2015",$110 Million,Willie Nelson,California
27,"July 04, 2015",$70 Million,Tom Rea,Missouri
28,"June 20, 2015",$80 Million,Orencia Barzey,Florida
29,"June 03, 2015",$188.9 Million,Maria Herrera,Arizona
30,"April 18, 2015",$50 Million,Anonymous,Puerto Rico
...,...,...,...,...
157,"May 28, 2005",$220.3 million,Brad Duke,Idaho
158,"March 30, 2005",$25.5 million,The Hubbard Family,Tennessee
159,"March 16, 2005",$18.7 million,Bob & Patty MacZura,Pennsylvania
160,"March 05, 2005",$19.9 million,Barbara & Craig Lennen,Indiana
161,"February 23, 2005",$18.7 million,Eric Kyle,Idaho
162,"February 12, 2005",$40.6 million,Duchess Trust,Louisiana
163,"January 22, 2005",$26.4 million,"Kathleen Fitzgerald, Karen Rodgers & Janet Bigler",Pennsylvania
164,"January 08, 2005",$36.8 million,Peter Bapes,Wisconsin
165,"December 22, 2004",$30.9 million,Tim Sindel,Arizona
166,"December 08, 2004",$171.4 million,WLT Trust,Pennsylvania
167,"October 16, 2004",14.4 million,Jacquelyn Moore,Iowa
168,"October 09, 2004",$214.7 million,33 Co-Workers from Seaford,Delaware
169,"August 14, 2004",$98.7 million,Mary Beth and David Wenell,Minnesota
170,"July 07, 2004",$21.1 million,Jackie and Jim Lagoon,Minnesota
171,"June 26, 2004",$65.8 million,Anonymous,South Carolina
172,"May 29, 2004",$52 million,Jim Hare & Tom Hare,Pennsylvania
173,"May 08, 2004",$213.2 million,Steve and Kristine White,Pennsylvania
174,"March 13, 2004",$89 million,Tim and Pam Rivers,Indiana
175,"February 04, 2004",$85.5 million,The Bow Trust,New Hampshire
176,"December 31, 2003",$221.5 million,Norman and DeAnna Shue,South Carolina
177,"November 05, 2003",$12.8 million,James and Rebeca Allen,Indiana
178,"October 29, 2003",$10 million,Jon & Louanne Lashbrook,Indiana
179,"October 25, 2003",$190.9 million,Regina Mandabach,Indiana
180,"August 30, 2003",$135 million,"Aeetos Trust, Rosemary Centola & Lawrence Centola",New Hampshire
181,"July 16, 2003",$13.5 million,"Alva ""Jeanie"" Osborne",Kentucky
182,"July 09, 2003",$261.3 million,William and Claudia Walkenbach,Missouri
183,"May 07, 2003",$88.7 million,Anthony and Monica Wilson,South Carolina
184,"March 26, 2003",$62.4 million,Hobert & Mary Parnell,West Virginia
185,"February 22, 2003",$42 million,"Cello Investments, LLC",Louisiana
186,"February 01, 2003",$101 million,Rondal Eaton,Indiana

In [11]:
lotto_path = 'data/master_lotto.csv'
lotto_master = pd.read_csv(lotto_path)
lotto_master.dtypes

Unnamed: 0             int64
DrawDate              object
WB1                    int64
WB2                    int64
WB3                    int64
WB4                    int64
WB5                    int64
PB                     int64
PP                   float64
estimated_jackpot     object
jackpot_winner        object
jackpot_option        object
dtype: object

In [12]:
lotto_master = lotto_master.drop(columns=['Unnamed: 0'])

In [13]:
lotto_master

,DrawDate,WB1,WB2,WB3,WB4,WB5,PB,PP,estimated_jackpot,jackpot_winner,jackpot_option
0,03/15/2017,30,16,41,48,53,16,3.0,$123 Million,Roll,NaN
1,03/11/2017,57,41,50,26,1,11,2.0,$104 Million,Roll,NaN
2,03/08/2017,42,23,59,46,33,4,2.0,$85 Million,Roll,NaN
3,03/04/2017,2,22,63,19,18,19,3.0,$68 Million,Roll,NaN
4,03/01/2017,16,10,52,40,55,17,10.0,$53 Million,Roll,NaN
5,02/25/2017,6,62,32,47,65,19,2.0,$40 Million,Roll,NaN
6,02/22/2017,52,10,61,28,13,2,2.0,$403 Million,Out of State Winner,NaN
7,02/18/2017,9,3,33,7,31,20,3.0,$349 Million,Roll,NaN
8,02/15/2017,33,5,42,38,28,19,2.0,$310 Million,Roll,NaN
9,02/11/2017,37,64,17,9,5,2,2.0,$285 Million,Roll,NaN
10,02/08/2017,49,20,42,14,66,5,2.0,$255 Million,Roll,NaN
11,02/04/2017,52,17,16,13,6,25,3.0,$229 Million,Roll,NaN
12,02/01/2017,9,60,64,43,57,10,2.0,$206 Million,Roll,NaN
13,01/28/2017,39,12,49,69,20,17,2.0,$187 Million,Roll,NaN
14,01/25/2017,18,62,66,68,28,22,2.0,$170 Million,Roll,NaN
15,01/21/2017,45,25,23,67,52,2,2.0,$153 Million,Roll,NaN
16,01/18/2017,41,9,58,40,53,12,2.0,$135 Million,Roll,NaN
17,01/14/2017,55,69,23,64,59,13,5.0,$121 Million,Roll,NaN
18,01/11/2017,1,16,13,43,3,24,2.0,$106 Million,Roll,NaN
19,01/07/2017,37,63,12,24,3,10,2.0,$94 Million,Roll,NaN
20,01/04/2017,17,16,42,41,29,4,3.0,$80 Million,Roll,NaN
21,12/31/2016,1,28,3,67,57,9,2.0,$70 Million,Roll,NaN
22,12/28/2016,30,23,44,58,16,4,2.0,$60 Million,Roll,NaN
23,12/24/2016,38,52,42,51,28,21,2.0,$50 Million,Roll,NaN
24,12/21/2016,25,68,40,54,33,3,5.0,$40 Million,Roll,NaN
25,12/17/2016,16,40,8,48,1,10,2.0,$119 Million,Out of State Winner,NaN
26,12/14/2016,39,18,66,37,26,15,3.0,$100 Million,Roll,NaN
27,12/10/2016,32,21,12,44,66,15,2.0,$85 Million,Roll,NaN
28,12/07/2016,49,64,48,41,53,20,2.0,$67 Million,Roll,NaN
29,12/03/2016,27,26,33,8,10,22,2.0,$54 Million,Roll,NaN
...,...,...,...,...,...,...,...,...,...,...,...
713,05/15/2010,28,15,36,23,21,20,2.0,$120 Million,Roll,NaN
714,05/12/2010,52,58,53,37,51,38,2.0,$97 Million,Roll,NaN
715,05/08/2010,41,5,57,34,22,31,5.0,$80 Million,Roll,NaN
716,05/05/2010,47,13,34,40,57,11,4.0,$60 Million,Roll,NaN
717,05/01/2010,23,25,16,49,58,20,4.0,$45 Million,Roll,NaN
718,04/28/2010,28,44,12,22,25,24,4.0,$30 Million,Roll,NaN
719,04/24/2010,57,56,1,53,12,5,2.0,$20 Million,Roll,NaN
720,04/21/2010,11,34,55,41,49,20,2.0,$252 Million,Out of State Winner,NaN
721,04/17/2010,22,41,49,21,5,15,5.0,$212 Million,Roll,NaN
722,04/14/2010,14,6,32,52,38,20,3.0,$175 Million,Roll,NaN
723,04/10/2010,21,22,52,49,58,34,2.0,$150 Million,Roll,NaN
724,04/07/2010,36,52,44,4,40,33,2.0,$125 Million,Roll,NaN
725,04/03/2010,15,59,52,10,31,4,4.0,$103 Million,Roll,NaN
726,03/31/2010,13,45,54,5,17,12,5.0,$81 Million,Roll,NaN
727,03/27/2010,21,7,32,52,44,10,4.0,$60 Million,Roll,NaN
728,03/24/2010,14,49,39,24,20,7,3.0,$43 Million,Roll,NaN
729,03/20/2010,9,36,44,45,39,9,2.0,$28 Million,Roll,NaN
730,03/17/2010,55,26,48,45,24,8,2.0,$20 Million,Roll,NaN
731,03/13/2010,16,36,20,6,31,8,5.0,$200 Million,Out of State Winner,NaN
732,03/10/2010,41,37,17,50,21,1,2.0,$170 Million,Roll,NaN
733,03/06/2010,41,33,10,59,29,15,2.0,$139 Million,Roll,NaN
734,03/03/2010,14,49,9,7,45,23,4.0,$114 Million,Roll,NaN
735,02/27/2010,47,18,58,53,51,30,2.0,$95 Million,Roll,NaN
736,02/24/2010,50,17,57,35,4,12,2.0,$76 Million,Roll,NaN
737,02/20/2010,13,54,41,37,27,32,2.0,$57 Million,Roll,NaN
738,02/17/2010,36,7,26,8,19,15,3.0,$40 Million,Roll,NaN
739,02/13/2010,14,10,40,51,30,1,4.0,$25 Million,Roll,NaN
740,02/10/2010,29,8,37,38,5,34,5.0,$20 Million,Roll,NaN
741,02/06/2010,22,54,52,14,59,4,3.0,$140 Million,Out of State Winner,NaN
742,02/03/2010,37,52,22,36,17,24,2.0,$115 Million,Roll,NaN

In [14]:
winning_states_df.dtypes

0
Draw Date        object
Jackpot Prize    object
Winner           object
State            object
dtype: object

In [15]:
winning_states_df['Draw Date']= pd.to_datetime(winning_states_df['Draw Date'])

In [16]:
# winning_states_df(winning_states_df['Draw Date'] > '02-03-2010')

winning_states_df = winning_states_df[winning_states_df['Draw Date'] > '02-03-2010']
winning_states_df = winning_states_df[winning_states_df['Draw Date'] < '03-22-2017']
winning_states_df

,Draw Date,Jackpot Prize,Winner,State
16,2017-02-22,$435.3 Million,"Bohemian Financial, LLC",Indiana
17,2016-12-17,$121.6 Million,Anonymous,DE
18,2016-11-26,$420.9 Million,Tennessee 20,Tennessee
19,2016-09-17,$246 Million,William and Heather ten Broeke,Georgia
20,2016-07-30,$487 Million,Robin Egg 2016 Nominee Trust,New Hampshire
21,2016-05-07,$284 Million,The Smith Family Lottery Pool,New Jersey
22,2016-03-02,$291.4 Million,James Stocklas,Florida
23,2016-01-13,$1.58 Billion,Marvin and Mae Acosta,California
24,2015-11-04,$144 Million,Avondale Revocable Trust,Tennessee
25,2015-09-30,$310 Million,Julie Leach,Michigan
26,2015-08-01,$110 Million,Willie Nelson,California
27,2015-07-04,$70 Million,Tom Rea,Missouri
28,2015-06-20,$80 Million,Orencia Barzey,Florida
29,2015-06-03,$188.9 Million,Maria Herrera,Arizona
30,2015-04-18,$50 Million,Anonymous,Puerto Rico
31,2015-04-11,$80 Million,Alice Dawson,Florida
32,2015-03-25,$40 Million,Rocklin Four,New Jersey
33,2015-03-21,$50 Million,Michael Duncan,Tennessee
34,2015-03-14,$136 Million,Unclaimed,New York
35,2015-02-11,$564 Million,Anonymous,Puerto Rico
36,2014-11-29,$90 Million,Lisa N. Quam,Washington
37,2014-11-08,$202.6 Million,Marilyn Boldon,Missouri
38,2014-09-24,$228 Million,Vinh Nguyen,California
39,2014-08-09,$90 Million,"Claude ""Al"" G.",Colorado
40,2014-07-19,$60 Million,"John ""Jack"" Long",California
41,2014-07-09,$124.9 Million,Mary Ann Thompson,Ohio
42,2014-06-11,$259 Million,Roy Cockrum,Tennessee
43,2014-04-23,$150 Million,FlaMass Family Lottery Joint Venture,Florida
44,2014-03-22,$96.5 Million,John and Susan Brands,Missouri
45,2014-03-01,$60 Million,Joseph Saxer,California
...,...,...,...,...
71,2012-03-07,$60 Million,Ohana Trust,Rhode Island
72,2012-02-25,$70 Million,Tara Ramirez/Case Park LLC,New York
73,2012-02-11,$336.4 Million,The Rainbow Sherbert Trust,Rhode Island
74,2011-12-24,$128.8 Million,Anonymous Winners,Maryland
75,2011-11-19,$59.9 Million,Steven Lloyd,Pennsylvania
76,2011-11-02,$254.2 Million,The Putnam Avenue Family Trust,Connecticut
77,2011-09-14,$25 Million,Kathy Scruggs,Georgia
78,2011-09-07,$108.8 Million,Name Withheld,Maryland
79,2011-08-10,$228.9 Million,Thomas Morris,Minnesota
80,2011-06-29,$77.1 Million,Unclaimed,Georgia
81,2011-06-08,$25.6 Million,Jimmy Freeman,Massachusetts
82,2011-06-01,$201.9 Million,1937 Flatbush Avenue Dodgers LLC,New York
83,2011-04-23,$74 Million,"William ""Bill"" Swanson II",Indiana
84,2011-04-06,$221 Million,Darin Fox and Todd Reardon,Indiana
85,2011-02-26,$184 million,Carvajal Family Group,Florida
86,2011-01-22,$122.1 Million,Stephen Kirwin,New York
87,2010-12-25,$48.8 Million,Jeffrey & Christine Pintuff,New York
88,2010-12-11,$37.5 million,Muncie Meade,Kentucky
89,2010-12-01,$95.3 million,Sheila Verke,Arizona
90,2010-11-06,$128.6 Million,Team Victory,Michigan
91,2010-10-06,$61.5 million,The Ziegler Family Revocable Trust,Florida
92,2010-09-18,$116 Million,Gerald L. Render,Georgia
93,2010-08-21,$79 million,"William R. ""Randy""",West Virginia
94,2010-07-31,$85.7 Million,H&N Family Partnership,Louisiana
95,2010-07-10,$73.9 Million,Elizabeth Choras-Hanna,Florida
96,2010-06-23,$97 million,The Lucky Thirteen Plus One,Ohio
97,2010-06-02,$261.6 million,The 2010 Blind Trust (George M. Hoffman),Ohio
98,2010-04-21,$258.5 Million,"Christopher ""Chris"" Shaw",Missouri
99,2010-03-13,$211.7 million,Sandra Mcneil,New Jersey
100,2010-02-06,$141.4 Million,Frank Griffin,North Carolina

In [17]:
winning_states_df['Draw Date'] = winning_states_df["Draw Date"].dt.strftime('%m-%d-%Y')

In [18]:
winning_states_df.head()

0    Draw Date   Jackpot Prize                          Winner          State
16  02-22-2017  $435.3 Million         Bohemian Financial, LLC        Indiana
17  12-17-2016  $121.6 Million                       Anonymous             DE
18  11-26-2016  $420.9 Million                    Tennessee 20      Tennessee
19  09-17-2016    $246 Million  William and Heather ten Broeke        Georgia
20  07-30-2016    $487 Million    Robin Egg 2016 Nominee Trust  New Hampshire

In [19]:
lotto_master.dtypes

DrawDate              object
WB1                    int64
WB2                    int64
WB3                    int64
WB4                    int64
WB5                    int64
PB                     int64
PP                   float64
estimated_jackpot     object
jackpot_winner        object
jackpot_option        object
dtype: object

In [20]:
lotto_master['DrawDate'] = pd.to_datetime(lotto_master['DrawDate']).dt.strftime('%m-%d-%Y')

In [21]:
lotto_master = lotto_master.rename(columns={'DrawDate':'Draw Date'})

In [22]:
lotto_master

,Draw Date,WB1,WB2,WB3,WB4,WB5,PB,PP,estimated_jackpot,jackpot_winner,jackpot_option
0,03-15-2017,30,16,41,48,53,16,3.0,$123 Million,Roll,NaN
1,03-11-2017,57,41,50,26,1,11,2.0,$104 Million,Roll,NaN
2,03-08-2017,42,23,59,46,33,4,2.0,$85 Million,Roll,NaN
3,03-04-2017,2,22,63,19,18,19,3.0,$68 Million,Roll,NaN
4,03-01-2017,16,10,52,40,55,17,10.0,$53 Million,Roll,NaN
5,02-25-2017,6,62,32,47,65,19,2.0,$40 Million,Roll,NaN
6,02-22-2017,52,10,61,28,13,2,2.0,$403 Million,Out of State Winner,NaN
7,02-18-2017,9,3,33,7,31,20,3.0,$349 Million,Roll,NaN
8,02-15-2017,33,5,42,38,28,19,2.0,$310 Million,Roll,NaN
9,02-11-2017,37,64,17,9,5,2,2.0,$285 Million,Roll,NaN
10,02-08-2017,49,20,42,14,66,5,2.0,$255 Million,Roll,NaN
11,02-04-2017,52,17,16,13,6,25,3.0,$229 Million,Roll,NaN
12,02-01-2017,9,60,64,43,57,10,2.0,$206 Million,Roll,NaN
13,01-28-2017,39,12,49,69,20,17,2.0,$187 Million,Roll,NaN
14,01-25-2017,18,62,66,68,28,22,2.0,$170 Million,Roll,NaN
15,01-21-2017,45,25,23,67,52,2,2.0,$153 Million,Roll,NaN
16,01-18-2017,41,9,58,40,53,12,2.0,$135 Million,Roll,NaN
17,01-14-2017,55,69,23,64,59,13,5.0,$121 Million,Roll,NaN
18,01-11-2017,1,16,13,43,3,24,2.0,$106 Million,Roll,NaN
19,01-07-2017,37,63,12,24,3,10,2.0,$94 Million,Roll,NaN
20,01-04-2017,17,16,42,41,29,4,3.0,$80 Million,Roll,NaN
21,12-31-2016,1,28,3,67,57,9,2.0,$70 Million,Roll,NaN
22,12-28-2016,30,23,44,58,16,4,2.0,$60 Million,Roll,NaN
23,12-24-2016,38,52,42,51,28,21,2.0,$50 Million,Roll,NaN
24,12-21-2016,25,68,40,54,33,3,5.0,$40 Million,Roll,NaN
25,12-17-2016,16,40,8,48,1,10,2.0,$119 Million,Out of State Winner,NaN
26,12-14-2016,39,18,66,37,26,15,3.0,$100 Million,Roll,NaN
27,12-10-2016,32,21,12,44,66,15,2.0,$85 Million,Roll,NaN
28,12-07-2016,49,64,48,41,53,20,2.0,$67 Million,Roll,NaN
29,12-03-2016,27,26,33,8,10,22,2.0,$54 Million,Roll,NaN
...,...,...,...,...,...,...,...,...,...,...,...
713,05-15-2010,28,15,36,23,21,20,2.0,$120 Million,Roll,NaN
714,05-12-2010,52,58,53,37,51,38,2.0,$97 Million,Roll,NaN
715,05-08-2010,41,5,57,34,22,31,5.0,$80 Million,Roll,NaN
716,05-05-2010,47,13,34,40,57,11,4.0,$60 Million,Roll,NaN
717,05-01-2010,23,25,16,49,58,20,4.0,$45 Million,Roll,NaN
718,04-28-2010,28,44,12,22,25,24,4.0,$30 Million,Roll,NaN
719,04-24-2010,57,56,1,53,12,5,2.0,$20 Million,Roll,NaN
720,04-21-2010,11,34,55,41,49,20,2.0,$252 Million,Out of State Winner,NaN
721,04-17-2010,22,41,49,21,5,15,5.0,$212 Million,Roll,NaN
722,04-14-2010,14,6,32,52,38,20,3.0,$175 Million,Roll,NaN
723,04-10-2010,21,22,52,49,58,34,2.0,$150 Million,Roll,NaN
724,04-07-2010,36,52,44,4,40,33,2.0,$125 Million,Roll,NaN
725,04-03-2010,15,59,52,10,31,4,4.0,$103 Million,Roll,NaN
726,03-31-2010,13,45,54,5,17,12,5.0,$81 Million,Roll,NaN
727,03-27-2010,21,7,32,52,44,10,4.0,$60 Million,Roll,NaN
728,03-24-2010,14,49,39,24,20,7,3.0,$43 Million,Roll,NaN
729,03-20-2010,9,36,44,45,39,9,2.0,$28 Million,Roll,NaN
730,03-17-2010,55,26,48,45,24,8,2.0,$20 Million,Roll,NaN
731,03-13-2010,16,36,20,6,31,8,5.0,$200 Million,Out of State Winner,NaN
732,03-10-2010,41,37,17,50,21,1,2.0,$170 Million,Roll,NaN
733,03-06-2010,41,33,10,59,29,15,2.0,$139 Million,Roll,NaN
734,03-03-2010,14,49,9,7,45,23,4.0,$114 Million,Roll,NaN
735,02-27-2010,47,18,58,53,51,30,2.0,$95 Million,Roll,NaN
736,02-24-2010,50,17,57,35,4,12,2.0,$76 Million,Roll,NaN
737,02-20-2010,13,54,41,37,27,32,2.0,$57 Million,Roll,NaN
738,02-17-2010,36,7,26,8,19,15,3.0,$40 Million,Roll,NaN
739,02-13-2010,14,10,40,51,30,1,4.0,$25 Million,Roll,NaN
740,02-10-2010,29,8,37,38,5,34,5.0,$20 Million,Roll,NaN
741,02-06-2010,22,54,52,14,59,4,3.0,$140 Million,Out of State Winner,NaN
742,02-03-2010,37,52,22,36,17,24,2.0,$115 Million,Roll,NaN

In [23]:
winning_states_df.head()

0    Draw Date   Jackpot Prize                          Winner          State
16  02-22-2017  $435.3 Million         Bohemian Financial, LLC        Indiana
17  12-17-2016  $121.6 Million                       Anonymous             DE
18  11-26-2016  $420.9 Million                    Tennessee 20      Tennessee
19  09-17-2016    $246 Million  William and Heather ten Broeke        Georgia
20  07-30-2016    $487 Million    Robin Egg 2016 Nominee Trust  New Hampshire

In [24]:
# pd.concat(lotto_master,winning_states_df)

In [25]:
winning_states_df = winning_states_df.rename(columns={'Draw Date':'Winning Date'})
winning_states_df.head()

0  Winning Date   Jackpot Prize                          Winner          State
16   02-22-2017  $435.3 Million         Bohemian Financial, LLC        Indiana
17   12-17-2016  $121.6 Million                       Anonymous             DE
18   11-26-2016  $420.9 Million                    Tennessee 20      Tennessee
19   09-17-2016    $246 Million  William and Heather ten Broeke        Georgia
20   07-30-2016    $487 Million    Robin Egg 2016 Nominee Trust  New Hampshire

In [26]:
lotto_master.dtypes

Draw Date             object
WB1                    int64
WB2                    int64
WB3                    int64
WB4                    int64
WB5                    int64
PB                     int64
PP                   float64
estimated_jackpot     object
jackpot_winner        object
jackpot_option        object
dtype: object

In [27]:
# lotto_concat = pd.concat([lotto_master, winning_states_df],axis=1)
# lotto_concat = lotto_concat.rename(columns={'estimated_jackpot':'EstimateJackpot','jackpot_winner':'JackpotWinner','jackpot_option':'JackpotOption'})

In [28]:
# lotto_concat.head()

In [38]:




result = pd.merge(lotto_master, winning_states_df[['Winning Date','Jackpot Prize', "Winner", "State"]], left_on='Draw Date',right_on='Winning Date',how='outer')

In [39]:
#result.to_csv('data/master_master.csv')

,Draw Date,WB1,WB2,WB3,WB4,WB5,PB,PP,estimated_jackpot,jackpot_winner,Jackpot Prize,Winner,State
0,03-15-2017,30,16,41,48,53,16,3.0,$123 Million,Roll,NaN,NaN,NaN
1,03-11-2017,57,41,50,26,1,11,2.0,$104 Million,Roll,NaN,NaN,NaN
2,03-08-2017,42,23,59,46,33,4,2.0,$85 Million,Roll,NaN,NaN,NaN
3,03-04-2017,2,22,63,19,18,19,3.0,$68 Million,Roll,NaN,NaN,NaN
4,03-01-2017,16,10,52,40,55,17,10.0,$53 Million,Roll,NaN,NaN,NaN
5,02-25-2017,6,62,32,47,65,19,2.0,$40 Million,Roll,NaN,NaN,NaN
6,02-22-2017,52,10,61,28,13,2,2.0,$403 Million,Out of State Winner,$435.3 Million,"Bohemian Financial, LLC",Indiana
7,02-18-2017,9,3,33,7,31,20,3.0,$349 Million,Roll,NaN,NaN,NaN
8,02-15-2017,33,5,42,38,28,19,2.0,$310 Million,Roll,NaN,NaN,NaN
9,02-11-2017,37,64,17,9,5,2,2.0,$285 Million,Roll,NaN,NaN,NaN
10,02-08-2017,49,20,42,14,66,5,2.0,$255 Million,Roll,NaN,NaN,NaN
11,02-04-2017,52,17,16,13,6,25,3.0,$229 Million,Roll,NaN,NaN,NaN
12,02-01-2017,9,60,64,43,57,10,2.0,$206 Million,Roll,NaN,NaN,NaN
13,01-28-2017,39,12,49,69,20,17,2.0,$187 Million,Roll,NaN,NaN,NaN
14,01-25-2017,18,62,66,68,28,22,2.0,$170 Million,Roll,NaN,NaN,NaN
15,01-21-2017,45,25,23,67,52,2,2.0,$153 Million,Roll,NaN,NaN,NaN
16,01-18-2017,41,9,58,40,53,12,2.0,$135 Million,Roll,NaN,NaN,NaN
17,01-14-2017,55,69,23,64,59,13,5.0,$121 Million,Roll,NaN,NaN,NaN
18,01-11-2017,1,16,13,43,3,24,2.0,$106 Million,Roll,NaN,NaN,NaN
19,01-07-2017,37,63,12,24,3,10,2.0,$94 Million,Roll,NaN,NaN,NaN
20,01-04-2017,17,16,42,41,29,4,3.0,$80 Million,Roll,NaN,NaN,NaN
21,12-31-2016,1,28,3,67,57,9,2.0,$70 Million,Roll,NaN,NaN,NaN
22,12-28-2016,30,23,44,58,16,4,2.0,$60 Million,Roll,NaN,NaN,NaN
23,12-24-2016,38,52,42,51,28,21,2.0,$50 Million,Roll,NaN,NaN,NaN
24,12-21-2016,25,68,40,54,33,3,5.0,$40 Million,Roll,NaN,NaN,NaN
25,12-17-2016,16,40,8,48,1,10,2.0,$119 Million,Out of State Winner,$121.6 Million,Anonymous,DE
26,12-14-2016,39,18,66,37,26,15,3.0,$100 Million,Roll,NaN,NaN,NaN
27,12-10-2016,32,21,12,44,66,15,2.0,$85 Million,Roll,NaN,NaN,NaN
28,12-07-2016,49,64,48,41,53,20,2.0,$67 Million,Roll,NaN,NaN,NaN
29,12-03-2016,27,26,33,8,10,22,2.0,$54 Million,Roll,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
713,05-15-2010,28,15,36,23,21,20,2.0,$120 Million,Roll,NaN,NaN,NaN
714,05-12-2010,52,58,53,37,51,38,2.0,$97 Million,Roll,NaN,NaN,NaN
715,05-08-2010,41,5,57,34,22,31,5.0,$80 Million,Roll,NaN,NaN,NaN
716,05-05-2010,47,13,34,40,57,11,4.0,$60 Million,Roll,NaN,NaN,NaN
717,05-01-2010,23,25,16,49,58,20,4.0,$45 Million,Roll,NaN,NaN,NaN
718,04-28-2010,28,44,12,22,25,24,4.0,$30 Million,Roll,NaN,NaN,NaN
719,04-24-2010,57,56,1,53,12,5,2.0,$20 Million,Roll,NaN,NaN,NaN
720,04-21-2010,11,34,55,41,49,20,2.0,$252 Million,Out of State Winner,$258.5 Million,"Christopher ""Chris"" Shaw",Missouri
721,04-17-2010,22,41,49,21,5,15,5.0,$212 Million,Roll,NaN,NaN,NaN
722,04-14-2010,14,6,32,52,38,20,3.0,$175 Million,Roll,NaN,NaN,NaN
723,04-10-2010,21,22,52,49,58,34,2.0,$150 Million,Roll,NaN,NaN,NaN
724,04-07-2010,36,52,44,4,40,33,2.0,$125 Million,Roll,NaN,NaN,NaN
725,04-03-2010,15,59,52,10,31,4,4.0,$103 Million,Roll,NaN,NaN,NaN
726,03-31-2010,13,45,54,5,17,12,5.0,$81 Million,Roll,NaN,NaN,NaN
727,03-27-2010,21,7,32,52,44,10,4.0,$60 Million,Roll,NaN,NaN,NaN
728,03-24-2010,14,49,39,24,20,7,3.0,$43 Million,Roll,NaN,NaN,NaN
729,03-20-2010,9,36,44,45,39,9,2.0,$28 Million,Roll,NaN,NaN,NaN
730,03-17-2010,55,26,48,45,24,8,2.0,$20 Million,Roll,NaN,NaN,NaN
731,03-13-2010,16,36,20,6,31,8,5.0,$200 Million,Out of State Winner,$211.7 million,Sandra Mcneil,New Jersey
732,03-10-2010,41,37,17,50,21,1,2.0,$170 Million,Roll,NaN,NaN,NaN
733,03-06-2010,41,33,10,59,29,15,2.0,$139 Million,Roll,NaN,NaN,NaN
734,03-03-2010,14,49,9,7,45,23,4.0,$114 Million,Roll,NaN,NaN,NaN
735,02-27-2010,47,18,58,53,51,30,2.0,$95 Million,Roll,NaN,NaN,NaN
736,02-24-2010,50,17,57,35,4,12,2.0,$76 Million,Roll,NaN,NaN,NaN
737,02-20-2010,13,54,41,37,27,32,2.0,$57 Million,Roll,NaN,NaN,NaN
738,02-17-2010,36,7,26,8,19,15,3.0,$40 Million,Roll,NaN,NaN,NaN
739,02-13-2010,14,10,40,51,30,1,4.0,$25 Million,Roll,NaN,NaN,NaN
740,02-10-2010,29,8,37,38,5,34,5.0,$20 Million,Roll,NaN,NaN,NaN
741,02-06-2010,22,54,52,14,59,4,3.0,$140 Million,Out of State Winner,$141.4 Million,Frank Griffin,North Carolina
742,02-03-2010,37,52,22,36,17,24,2.0,$115 Million,Roll,NaN,NaN,NaN

In [45]:
result_master = result.fillna('LOSER')

In [46]:
result_master

,Draw Date,WB1,WB2,WB3,WB4,WB5,PB,PP,estimated_jackpot,jackpot_winner,Jackpot Prize,Winner,State
0,03-15-2017,30,16,41,48,53,16,3,$123 Million,Roll,LOSER,LOSER,LOSER
1,03-11-2017,57,41,50,26,1,11,2,$104 Million,Roll,LOSER,LOSER,LOSER
2,03-08-2017,42,23,59,46,33,4,2,$85 Million,Roll,LOSER,LOSER,LOSER
3,03-04-2017,2,22,63,19,18,19,3,$68 Million,Roll,LOSER,LOSER,LOSER
4,03-01-2017,16,10,52,40,55,17,10,$53 Million,Roll,LOSER,LOSER,LOSER
5,02-25-2017,6,62,32,47,65,19,2,$40 Million,Roll,LOSER,LOSER,LOSER
6,02-22-2017,52,10,61,28,13,2,2,$403 Million,Out of State Winner,$435.3 Million,"Bohemian Financial, LLC",Indiana
7,02-18-2017,9,3,33,7,31,20,3,$349 Million,Roll,LOSER,LOSER,LOSER
8,02-15-2017,33,5,42,38,28,19,2,$310 Million,Roll,LOSER,LOSER,LOSER
9,02-11-2017,37,64,17,9,5,2,2,$285 Million,Roll,LOSER,LOSER,LOSER
10,02-08-2017,49,20,42,14,66,5,2,$255 Million,Roll,LOSER,LOSER,LOSER
11,02-04-2017,52,17,16,13,6,25,3,$229 Million,Roll,LOSER,LOSER,LOSER
12,02-01-2017,9,60,64,43,57,10,2,$206 Million,Roll,LOSER,LOSER,LOSER
13,01-28-2017,39,12,49,69,20,17,2,$187 Million,Roll,LOSER,LOSER,LOSER
14,01-25-2017,18,62,66,68,28,22,2,$170 Million,Roll,LOSER,LOSER,LOSER
15,01-21-2017,45,25,23,67,52,2,2,$153 Million,Roll,LOSER,LOSER,LOSER
16,01-18-2017,41,9,58,40,53,12,2,$135 Million,Roll,LOSER,LOSER,LOSER
17,01-14-2017,55,69,23,64,59,13,5,$121 Million,Roll,LOSER,LOSER,LOSER
18,01-11-2017,1,16,13,43,3,24,2,$106 Million,Roll,LOSER,LOSER,LOSER
19,01-07-2017,37,63,12,24,3,10,2,$94 Million,Roll,LOSER,LOSER,LOSER
20,01-04-2017,17,16,42,41,29,4,3,$80 Million,Roll,LOSER,LOSER,LOSER
21,12-31-2016,1,28,3,67,57,9,2,$70 Million,Roll,LOSER,LOSER,LOSER
22,12-28-2016,30,23,44,58,16,4,2,$60 Million,Roll,LOSER,LOSER,LOSER
23,12-24-2016,38,52,42,51,28,21,2,$50 Million,Roll,LOSER,LOSER,LOSER
24,12-21-2016,25,68,40,54,33,3,5,$40 Million,Roll,LOSER,LOSER,LOSER
25,12-17-2016,16,40,8,48,1,10,2,$119 Million,Out of State Winner,$121.6 Million,Anonymous,DE
26,12-14-2016,39,18,66,37,26,15,3,$100 Million,Roll,LOSER,LOSER,LOSER
27,12-10-2016,32,21,12,44,66,15,2,$85 Million,Roll,LOSER,LOSER,LOSER
28,12-07-2016,49,64,48,41,53,20,2,$67 Million,Roll,LOSER,LOSER,LOSER
29,12-03-2016,27,26,33,8,10,22,2,$54 Million,Roll,LOSER,LOSER,LOSER
...,...,...,...,...,...,...,...,...,...,...,...,...,...
713,05-15-2010,28,15,36,23,21,20,2,$120 Million,Roll,LOSER,LOSER,LOSER
714,05-12-2010,52,58,53,37,51,38,2,$97 Million,Roll,LOSER,LOSER,LOSER
715,05-08-2010,41,5,57,34,22,31,5,$80 Million,Roll,LOSER,LOSER,LOSER
716,05-05-2010,47,13,34,40,57,11,4,$60 Million,Roll,LOSER,LOSER,LOSER
717,05-01-2010,23,25,16,49,58,20,4,$45 Million,Roll,LOSER,LOSER,LOSER
718,04-28-2010,28,44,12,22,25,24,4,$30 Million,Roll,LOSER,LOSER,LOSER
719,04-24-2010,57,56,1,53,12,5,2,$20 Million,Roll,LOSER,LOSER,LOSER
720,04-21-2010,11,34,55,41,49,20,2,$252 Million,Out of State Winner,$258.5 Million,"Christopher ""Chris"" Shaw",Missouri
721,04-17-2010,22,41,49,21,5,15,5,$212 Million,Roll,LOSER,LOSER,LOSER
722,04-14-2010,14,6,32,52,38,20,3,$175 Million,Roll,LOSER,LOSER,LOSER
723,04-10-2010,21,22,52,49,58,34,2,$150 Million,Roll,LOSER,LOSER,LOSER
724,04-07-2010,36,52,44,4,40,33,2,$125 Million,Roll,LOSER,LOSER,LOSER
725,04-03-2010,15,59,52,10,31,4,4,$103 Million,Roll,LOSER,LOSER,LOSER
726,03-31-2010,13,45,54,5,17,12,5,$81 Million,Roll,LOSER,LOSER,LOSER
727,03-27-2010,21,7,32,52,44,10,4,$60 Million,Roll,LOSER,LOSER,LOSER
728,03-24-2010,14,49,39,24,20,7,3,$43 Million,Roll,LOSER,LOSER,LOSER
729,03-20-2010,9,36,44,45,39,9,2,$28 Million,Roll,LOSER,LOSER,LOSER
730,03-17-2010,55,26,48,45,24,8,2,$20 Million,Roll,LOSER,LOSER,LOSER
731,03-13-2010,16,36,20,6,31,8,5,$200 Million,Out of State Winner,$211.7 million,Sandra Mcneil,New Jersey
732,03-10-2010,41,37,17,50,21,1,2,$170 Million,Roll,LOSER,LOSER,LOSER
733,03-06-2010,41,33,10,59,29,15,2,$139 Million,Roll,LOSER,LOSER,LOSER
734,03-03-2010,14,49,9,7,45,23,4,$114 Million,Roll,LOSER,LOSER,LOSER
735,02-27-2010,47,18,58,53,51,30,2,$95 Million,Roll,LOSER,LOSER,LOSER
736,02-24-2010,50,17,57,35,4,12,2,$76 Million,Roll,LOSER,LOSER,LOSER
737,02-20-2010,13,54,41,37,27,32,2,$57 Million,Roll,LOSER,LOSER,LOSER
738,02-17-2010,36,7,26,8,19,15,3,$40 Million,Roll,LOSER,LOSER,LOSER
739,02-13-2010,14,10,40,51,30,1,4,$25 Million,Roll,LOSER,LOSER,LOSER
740,02-10-2010,29,8,37,38,5,34,5,$20 Million,Roll,LOSER,LOSER,LOSER
741,02-06-2010,22,54,52,14,59,4,3,$140 Million,Out of State Winner,$141.4 Million,Frank Griffin,North Carolina
742,02-03-2010,37,52,22,36,17,24,2,$115 Million,Roll,LOSER,LOSER,LOSER

In [47]:
from sqlalchemy import create_engine
import mysql.connector
SQLUSER = 'root'
SQLPASS = ''
SQLHOST = 'localhost'
SQLPORT = '3306'
engine = create_engine(f'mysql+mysqlconnector://{SQLUSER}:{SQLPASS}@{SQLHOST}:{SQLPORT}')
conn = engine.connect()
conn.execute('DROP DATABASE IF EXISTS lottery;')
conn.execute("CREATE DATABASE lottery")
lottery_database = engine.execute("USE lottery;")
result_master.to_sql(name='powerball', con=engine, if_exists = 'replace', index=False)
data = pd.read_sql('SELECT * FROM powerball', engine)

In [48]:
data

,Draw Date,WB1,WB2,WB3,WB4,WB5,PB,PP,estimated_jackpot,jackpot_winner,Jackpot Prize,Winner,State
0,03-15-2017,30,16,41,48,53,16,3.0,$123 Million,Roll,LOSER,LOSER,LOSER
1,03-11-2017,57,41,50,26,1,11,2.0,$104 Million,Roll,LOSER,LOSER,LOSER
2,03-08-2017,42,23,59,46,33,4,2.0,$85 Million,Roll,LOSER,LOSER,LOSER
3,03-04-2017,2,22,63,19,18,19,3.0,$68 Million,Roll,LOSER,LOSER,LOSER
4,03-01-2017,16,10,52,40,55,17,10.0,$53 Million,Roll,LOSER,LOSER,LOSER
5,02-25-2017,6,62,32,47,65,19,2.0,$40 Million,Roll,LOSER,LOSER,LOSER
6,02-22-2017,52,10,61,28,13,2,2.0,$403 Million,Out of State Winner,$435.3 Million,"Bohemian Financial, LLC",Indiana
7,02-18-2017,9,3,33,7,31,20,3.0,$349 Million,Roll,LOSER,LOSER,LOSER
8,02-15-2017,33,5,42,38,28,19,2.0,$310 Million,Roll,LOSER,LOSER,LOSER
9,02-11-2017,37,64,17,9,5,2,2.0,$285 Million,Roll,LOSER,LOSER,LOSER
10,02-08-2017,49,20,42,14,66,5,2.0,$255 Million,Roll,LOSER,LOSER,LOSER
11,02-04-2017,52,17,16,13,6,25,3.0,$229 Million,Roll,LOSER,LOSER,LOSER
12,02-01-2017,9,60,64,43,57,10,2.0,$206 Million,Roll,LOSER,LOSER,LOSER
13,01-28-2017,39,12,49,69,20,17,2.0,$187 Million,Roll,LOSER,LOSER,LOSER
14,01-25-2017,18,62,66,68,28,22,2.0,$170 Million,Roll,LOSER,LOSER,LOSER
15,01-21-2017,45,25,23,67,52,2,2.0,$153 Million,Roll,LOSER,LOSER,LOSER
16,01-18-2017,41,9,58,40,53,12,2.0,$135 Million,Roll,LOSER,LOSER,LOSER
17,01-14-2017,55,69,23,64,59,13,5.0,$121 Million,Roll,LOSER,LOSER,LOSER
18,01-11-2017,1,16,13,43,3,24,2.0,$106 Million,Roll,LOSER,LOSER,LOSER
19,01-07-2017,37,63,12,24,3,10,2.0,$94 Million,Roll,LOSER,LOSER,LOSER
20,01-04-2017,17,16,42,41,29,4,3.0,$80 Million,Roll,LOSER,LOSER,LOSER
21,12-31-2016,1,28,3,67,57,9,2.0,$70 Million,Roll,LOSER,LOSER,LOSER
22,12-28-2016,30,23,44,58,16,4,2.0,$60 Million,Roll,LOSER,LOSER,LOSER
23,12-24-2016,38,52,42,51,28,21,2.0,$50 Million,Roll,LOSER,LOSER,LOSER
24,12-21-2016,25,68,40,54,33,3,5.0,$40 Million,Roll,LOSER,LOSER,LOSER
25,12-17-2016,16,40,8,48,1,10,2.0,$119 Million,Out of State Winner,$121.6 Million,Anonymous,DE
26,12-14-2016,39,18,66,37,26,15,3.0,$100 Million,Roll,LOSER,LOSER,LOSER
27,12-10-2016,32,21,12,44,66,15,2.0,$85 Million,Roll,LOSER,LOSER,LOSER
28,12-07-2016,49,64,48,41,53,20,2.0,$67 Million,Roll,LOSER,LOSER,LOSER
29,12-03-2016,27,26,33,8,10,22,2.0,$54 Million,Roll,LOSER,LOSER,LOSER
...,...,...,...,...,...,...,...,...,...,...,...,...,...
713,05-15-2010,28,15,36,23,21,20,2.0,$120 Million,Roll,LOSER,LOSER,LOSER
714,05-12-2010,52,58,53,37,51,38,2.0,$97 Million,Roll,LOSER,LOSER,LOSER
715,05-08-2010,41,5,57,34,22,31,5.0,$80 Million,Roll,LOSER,LOSER,LOSER
716,05-05-2010,47,13,34,40,57,11,4.0,$60 Million,Roll,LOSER,LOSER,LOSER
717,05-01-2010,23,25,16,49,58,20,4.0,$45 Million,Roll,LOSER,LOSER,LOSER
718,04-28-2010,28,44,12,22,25,24,4.0,$30 Million,Roll,LOSER,LOSER,LOSER
719,04-24-2010,57,56,1,53,12,5,2.0,$20 Million,Roll,LOSER,LOSER,LOSER
720,04-21-2010,11,34,55,41,49,20,2.0,$252 Million,Out of State Winner,$258.5 Million,"Christopher ""Chris"" Shaw",Missouri
721,04-17-2010,22,41,49,21,5,15,5.0,$212 Million,Roll,LOSER,LOSER,LOSER
722,04-14-2010,14,6,32,52,38,20,3.0,$175 Million,Roll,LOSER,LOSER,LOSER
723,04-10-2010,21,22,52,49,58,34,2.0,$150 Million,Roll,LOSER,LOSER,LOSER
724,04-07-2010,36,52,44,4,40,33,2.0,$125 Million,Roll,LOSER,LOSER,LOSER
725,04-03-2010,15,59,52,10,31,4,4.0,$103 Million,Roll,LOSER,LOSER,LOSER
726,03-31-2010,13,45,54,5,17,12,5.0,$81 Million,Roll,LOSER,LOSER,LOSER
727,03-27-2010,21,7,32,52,44,10,4.0,$60 Million,Roll,LOSER,LOSER,LOSER
728,03-24-2010,14,49,39,24,20,7,3.0,$43 Million,Roll,LOSER,LOSER,LOSER
729,03-20-2010,9,36,44,45,39,9,2.0,$28 Million,Roll,LOSER,LOSER,LOSER
730,03-17-2010,55,26,48,45,24,8,2.0,$20 Million,Roll,LOSER,LOSER,LOSER
731,03-13-2010,16,36,20,6,31,8,5.0,$200 Million,Out of State Winner,$211.7 million,Sandra Mcneil,New Jersey
732,03-10-2010,41,37,17,50,21,1,2.0,$170 Million,Roll,LOSER,LOSER,LOSER
733,03-06-2010,41,33,10,59,29,15,2.0,$139 Million,Roll,LOSER,LOSER,LOSER
734,03-03-2010,14,49,9,7,45,23,4.0,$114 Million,Roll,LOSER,LOSER,LOSER
735,02-27-2010,47,18,58,53,51,30,2.0,$95 Million,Roll,LOSER,LOSER,LOSER
736,02-24-2010,50,17,57,35,4,12,2.0,$76 Million,Roll,LOSER,LOSER,LOSER
737,02-20-2010,13,54,41,37,27,32,2.0,$57 Million,Roll,LOSER,LOSER,LOSER
738,02-17-2010,36,7,26,8,19,15,3.0,$40 Million,Roll,LOSER,LOSER,LOSER
739,02-13-2010,14,10,40,51,30,1,4.0,$25 Million,Roll,LOSER,LOSER,LOSER
740,02-10-2010,29,8,37,38,5,34,5.0,$20 Million,Roll,LOSER,LOSER,LOSER
741,02-06-2010,22,54,52,14,59,4,3.0,$140 Million,Out of State Winner,$141.4 Million,Frank Griffin,North Carolina
742,02-03-2010,37,52,22,36,17,24,2.0,$115 Million,Roll,LOSER,LOSER,LOSER